---
title: "Ad Stock Effection"
output: html_notebook
---

### 時点を考慮した動的モデル

静的市場反応モデル

$$y_t=x^0_t\beta_0 + x^1_t\beta_1 + e_t ~~~~~e_t\sim N(0,\sigma^2) $$

動的市場反応モデル

$$y_t=x^0_t\beta_0,_t + x^1_t\beta_1,_t + e_t ~~~~~e_t\sim N(0,\sigma^2) $$

観測モデルの拡張イメージ

$$y_t=x^0_t\beta_0,_t + x^1_t\beta_1,_t + x^2_tStock_t + e_t ~~~~~e_t\sim N(0,\sigma^2) \\
Stock_t=\lambda \times Stock_{t-1} + (1-\lambda) \times GRP_t$$
  


### 自動車会社ごとにStockについて検証してα決める

α（残存率）0-0.95まで0.05きざみでストックパターンをすべて計算
左端（1期）のデータは外す（ストックの時をのぞく）->AICで比較するため全部2日目からみるようにする
各モデルでAICを計算して一番小さいモデルが妥当なStockとみなす

```{r}
library(dlm)
library(dplyr)
query<-read.csv("suzuki/daily.csv",sep="\t")
grp<-read.csv("suzuki/grp.csv")
# 検索数前処理
q <- query %>%
  dplyr::select(StartDate,Queries) %>%
  dplyr::group_by(date=as.Date(StartDate)) %>%
  dplyr::summarise(query = sum(Queries))

# 視聴数を単純に日別集計
g<- grp %>%
  dplyr::select(date,person) %>%
  dplyr::group_by(date=as.Date(date)) %>%
  dplyr::summarise(grp = sum(person))
g[is.na(g)]<-0

#視聴率と検索を結合
d <- dplyr::inner_join(q,g,by="date")
y<-log(d$query)
x1<-log(d$grp)
#plot(d$grp~d$date, type="l")
```

```{r}
# ストックを入れない時の効果
  build.1 <- function(params){
    dlmModReg(x1, dV = exp(params[1]), dW = exp(params[2:3]))
  }
  fit.1 <- dlmMLE(y,rep(0,3),build.1,hessian=T)
    -2*fit.1$value+2*3
```


### Calculate Advertising Adstock
```{r}
# http://stackoverflow.com/questions/14372880/simple-examples-of-filter-function-recursive-option-specifically


adstock <- function(adstock_rate) {
  # Alternative Method Using Loops Proposed by Linh Tran
  #adstock_rate=0
   stock = numeric(length(d$grp))
   stock[1] = mean(d$grp)
   for(i in 2:length(d$grp)){
   stock[i] = (1-adstock_rate)*d$grp[i-1] + adstock_rate * stock[i-1]
  }
 #stock = stats::filter(d$grp, filter=adstock_rate, method="recursive" ,init=mean(d$grp))
  y<-log(d$query)
  x1<-log(d$grp)
  x2<-log(stock) 
  x<-cbind(x1,x2)
  # x(grp,ストック)が説明変数,dWには切片と回帰係数2個の分散入力、ここを固定にすると時変しなくなる
  build.1 <- function(params){
    dlmModReg(x, dV = exp(params[1]), dW = exp(params[2:4]))
  }
  fit.1 <- dlmMLE(y,rep(0,4),build.1,hessian=T)
  # AIC.αがパラメータ数として追加されるので4+1=5
  # パラメータが1増えると罰則が2増える(パラメータ数が低いモデルの方が良いとされるため=けちの原理)
    -2*fit.1$value+2*5
}
```


```{r}
adstock(0.5)
```


```{r}
aic = numeric(9)
for(i in 1:9){
  aic[i]<-adstock(i*0.1)
  print(i*0.1)
  print(aic[i])
}
```







### Networkごとの検証

*時間帯はいまいちでは？
時間帯で考える場合はすべての会社のデータを統合すべきでは？


Networkは相互相関を考える必要があるがdlmでなくプログラミング必要

### 週末効果
